version: '3.8'

services:
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  web:
    build: ./webapp
    ports:
      - "80:5000"
    volumes:
      - ./webapp:/app

volumes:
  jenkins_home:
